### ISSUE TITLE
Make the PBTY logo

### ISSUE THREAD

**Issue by opcryptogroot** [opcryptogroot/Guardians-Of-The-Galaxy#6]
This token represents ETH used as bounty to remove Putin from power.
The logo can be a representation of Putin on the top of which a "cancel" symbol (https://duckduckgo.com/?q=cancel&ia=images&iax=images&iai=https%3A%2F%2Fclipground.com%2Fimages%2Fcancel-png-20.png) is added.
Other ideas can be explored too.

**Comment by hashedpip** [comment]
Suggested Icon:

![Group 36](https://user-images.githubusercontent.com/103964110/184881876-23e5d46c-32a9-4860-b2ce-7aadfce07825.png)

**Comment by hashedpip** [comment]
@opcryptogroot

**Comment by opcryptogroot** [comment]
This logo is good.
