### ISSUE TITLE
Make the GUARD logo

### ISSUE THREAD

**Issue by opcryptogroot** [opcryptogroot/Guardians-Of-The-Galaxy#7]
This logo is for the Guardian token of the Guardian DAO.
We want to represent that it is protecting the world from attacks.
We can have a galaxy protected by a shield or any other idea presenting a similar concept.

**Comment by hashedpip** [comment]
suggestion 1:

<p align="center">
  <img width=40% src="https://user-images.githubusercontent.com/103964110/184882184-f9f3f2d7-b8df-404b-a8cc-303a493b02c2.png" alt="Guard 1"/>
</p>

suggestion 2:

<p align="center">
  <img width=40% src="https://user-images.githubusercontent.com/103964110/184927635-a4d25928-7514-4c09-8042-489c23f746d8.png" alt="Guard 2"/>
</p>

**Comment by hashedpip** [comment]
@opcryptogroot

**Comment by opcryptogroot** [comment]
I prefer the first suggestion which is more abstract and best fit the current website look. Let's go with 1.
